music/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views
from music.views import output, saveAnswer,check,go,signup,sample_view,show_notification

app_name='music'
# SamsadSajid
urlpatterns = [
    #/music/
    url(r'^$',views.LogInFormView.as_view(),name='login'),
#url(r'badhon',go,name='badhon'),
    url(r'^home',sample_view, name='home'),

    url(r'^SignIn',views.UserFormView.as_view(),name='signin'),
    #/music/album_id/
    #url(r'^home',views.IndexView.as_view(),name='home'),
    url(r'^register',views.UserFormView.as_view(),name='register'),
    #url(r'^login',views.login(),name='login'),
    url(r'^(?P<pk>[0-9]+)', output,name='detail1'),
    url(r'^question/(?P<pk>[0-9]+)/ans', saveAnswer, name='detail'),

    #/music/album_id/favourite/
    #url(r'^(?P<album_id>[0-9]+)/favourite',views.favourite,name='favourite'),
    url(r'^album/add',views.AlbumCreate.as_view(),name='album-add'),

    url(r'^album/add',views.AlbumCreate.as_view(),name='album-add'),

    url(r'^askquestion',views.QuestionFormView.as_view(),name='ask_question'),

    url(r'^answer/(?P<pk>[0-9]+)',views.AnswerFormView.as_view(),name='answer'),
    url(r'^success',check,name='succ'),
    url(r'^getstart',signup,name='signup'),
    url(r'^notification/(?P<key>[0-9]+)',show_notification,name='notification'),
    url(r'^answer/vote/',views.vote,name='vote'),
    url(r'^search/', views.search, name='search'),
    url(r'^menu/(?P<string>[A-Za-z]+)',views.menu,name='menu'),

    #url(r'^search/(?P<>[A-Za-)', signup, name='signup'),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),


]

music/models.py
# -*- coding: utf-8 -*-


from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime
from Activity.models import Activity
class Album(models.Model):
     artist = models.CharField(max_length=270)
     album_title=models.CharField(max_length=500)
     genre=models.CharField(max_length=100)
     album_logo = models.CharField(max_length=1000)

     def get_absolute_url(self):
          return reverse('music:detail',kwargs={'pk':self.pk})

     def __str__(self):
          return self.album_title + '-' + self.artist
class Song(models.Model):
     album = models.ForeignKey(Album,on_delete=models.CASCADE)
     file_type=models.CharField(max_length=50)
     song_title=models.CharField(max_length=100)
     is_favourite = models.BooleanField(default=False)
     def __str__(self):
          return self.song_title

class Question(models.Model):
     text = models.CharField(max_length=400)
     tag = models.CharField(max_length=50)
     person=models.CharField(max_length=40)

     date = models.DateTimeField(default=datetime.now, blank=True)





#class Answer(models.Model):
     #question = models.ForeignKey(Question,on_delete=models.CASCADE())
     #text = models.CharField(max_length=300)


class Answer(models.Model):
    #user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    description = models.TextField(max_length=2000)
    person=models.CharField(max_length=50)
    date = models.DateTimeField(default=datetime.now, blank=True)
    votes = models.IntegerField(default=0)

    def calculate_votes(self):
         up_votes = Activity.objects.filter(activity_type=Activity.UP_VOTE,
                                            answer=self.pk).count()
         down_votes = Activity.objects.filter(activity_type=Activity.DOWN_VOTE,
                                              answer=self.pk).count()
         self.votes = up_votes - down_votes
         self.save()
         return self.votes

    def get_up_voters(self):
         votes = Activity.objects.filter(activity_type=Activity.UP_VOTE,
                                         answer=self.pk)
         voters = []
         for vote in votes:
              voters.append(vote.user)
         return voters

    def get_down_voters(self):
         votes = Activity.objects.filter(activity_type=Activity.DOWN_VOTE,
                                         answer=self.pk)
         voters = []
         for vote in votes:
              voters.append(vote.user)
         return voters

    #create_date = models.DateTimeField(auto_now_add=True)
    #update_date = models.DateTimeField(null=True, blank=True)
    #votes = models.IntegerField(default=0)
    #is_accepted = models.BooleanField(default=False)

class Notification(models.Model):
     message=models.CharField(max_length=200)
     #message=models.TextField()
     viewed=models.BooleanField(default=False,editable=True)
     user=models.ForeignKey(User)
     question=models.ForeignKey(Question)

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LogForm(forms.ModelForm):
    username=forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','password']

music/views.py
from django.contrib import messages
from django.views import generic
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic import View

from .models import Album, Question,Answer,Notification
from .forms import UserForm,LogForm
from .questionform import QuestForm,AnswerForm
from Activity.models import Activity
from django.db.models import Q
from django.http import HttpResponse, HttpResponseForbidden
from django.db.models import DateTimeField
from django.db.models.functions import Trunc
from django.shortcuts import render_to_response


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_question'



    def get_queryset(self):
        return Question.objects.all()












class DetailView(generic.DeleteView):
    model = Question
    template_name = 'music/qst1.html'


class AlbumCreate(CreateView):
    model=Album
    fields = ['artist','album_title','genre','album_logo ']






class UserFormView(View):
    form_class=UserForm
    template_name='music/registration_form.html'
    #display blank form
    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})


    #process form data
    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            print("hiiiiiiii")
            user = form.save(commit=False)

            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username,password=password)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('music:home')

        return render(request, self.template_name, {'form': form})

class LogInFormView(View):
    form_class=LogForm
    template_name = 'music/start2.html'


    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):


        form = self.form_class(request.POST)
        print (form)

        if form.is_valid():
            print("Dipan")
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            #user.set_password(password)

            #user.save()
            print(username,password)
            user = authenticate(request,username=username, password=password)
            if user is not None:
                print("log in")
                if user.is_active:
                    login(request, user)
                    return redirect('music:home')
            else:
                 # print("log in")
                return redirect('music:login')

        return render(request, self.template_name, {'form': form})


class QuestionFormView(View):
    form_class=QuestForm
    template_name = 'music/question_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form,'id':request.user.id})


    #process form data
    def post(self,request):
        form=self.form_class(request.POST)
        current_user=request.user
        # print(form)
        if form.is_valid():
            question = form.save(commit=False)
            ques_text = form.cleaned_data['ques_text']
            ques_tag = form.cleaned_data['ques_tag']
            # print(ques_text)
            # print(ques_tag)
            qsn = Question(text=ques_text, tag=ques_tag,person=current_user.username)
            qsn.save()
        all_questions=Question.objects.all()
        page = request.GET.get('page', 1)
        current_user = request.user

        paginator = Paginator(all_questions, 4)
        try:
            allqsts = paginator.page(page)
        except PageNotAnInteger:
            allqsts = paginator.page(1)
        except EmptyPage:
            allqsts = paginator.page(paginator.num_pages)

        # return render(request, 'music/index2.html',
        #               {'all_question': all_questions, 'username': current_user.username, 'id': current_user.id})

        return redirect('home/')









class AnswerFormView(View):
    form_class=AnswerForm
    template_name = 'music/answer_form.html'

    def get(self,request, pk):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form,'question':pk,'id':request.user.id})


    #process form data
    def post(self,request):
        form=self.form_class(request.POST)
        # print(form)
        if form.is_valid():
            answer = form.save(commit=False)
            question = form.cleaned_data['question']
            description = form.cleaned_data['description']

            ans = Answer(question=question,description=description)
            ans.save()
        return render(request, self.template_name, {'form': form})



def output(request, pk):
    notifications=Notification.objects.all()
    qtion=Question.objects.get(id=pk)
    print (pk)
    for notification in notifications:
        # print (notification.question.id)
        if(notification.question.id==qtion.id):
            # print ("okkkkkk")
            notification.viewed=True
            notification.save()
            #print (notification.viewed)

    question=Question.objects.filter(id=pk)
    print()
    answer=Answer.objects.filter(question=question)
    form=AnswerForm()

    return render(request, 'music/qst1.html',{'answers':answer,'id':request.user.id,'question':qtion})

def saveAnswer(request, pk):
    question = Question.objects.get(id=pk)
    qst_prsn=question.person
    user=User.objects.get(username=qst_prsn)
    current_user=request.user
    ans_prsn=current_user.username
    string=ans_prsn + "has answered your question"
    notification_entry=Notification(message=string,user=user,question=question)
    notification_entry.save()
    #print(question.person)

    form=AnswerForm(request.POST)
    print(form)
    if form.is_valid():
        print("form is valid")
        answer = form.save(commit=False)
        #question = form.cleaned_data['question']
        description = form.cleaned_data['description']

        ans = Answer(description=description,person=current_user.username, question= question)
        ans.save()
    question1 = Question.objects.get(id=pk)

    answer1 = Answer.objects.filter(question=question1)


    return render(request, 'music/qst1.html',{'answers':answer1,'id':request.user.id,'question':question1})

def check(request):
    all_questions=Question.objects.all()
    page = request.GET.get('page', 1)
    current_user = request.user

    paginator = Paginator(all_questions,4)
    try:
        allqsts = paginator.page(page)
    except PageNotAnInteger:
       allqsts = paginator.page(1)
    except EmptyPage:
        allqsts = paginator.page(paginator.num_pages)

    # all_questions.objects.order_by(
    #     Trunc('date', 'date', output_field=DateTimeField()).desc(),
    #     '-score')

    if request.method == 'POST':
        #print ("dibya")
        # form=UserForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        #print (username,password)
        #name(username)
        user = authenticate(request, username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)


                return render(request, 'music/index2.html',
                              {'all_question': allqsts, 'username': current_user.username,'id':current_user.id})
        else:
            # print ("No user detected")
            messages.add_message(request, messages.ERROR, "Username or Paswword"
                                " is invalid")
            return render(request, 'music/Start2.html')

    return render(request, 'music/index2.html',
                          {'all_question': allqsts, 'username': current_user.username, 'id': current_user.id})
    # if form.is_valid():
    #     print("form is valid")
    #     username = form.cleaned_data['username']
    #     password = form.cleaned_data['password']
    #     print(username, password)
    # return render(request, 'music/index.html')

def go(request):
    return render(request,'music/badhon.html')

def signup(request):
    all_questions = Question.objects.all()
    page = request.GET.get('page', 1)
    current_user = request.user

    paginator = Paginator(all_questions, 4)
    try:
        allqsts = paginator.page(page)
    except PageNotAnInteger:
        allqsts = paginator.page(1)
    except EmptyPage:
        allqsts = paginator.page(paginator.num_pages)

    # if request.method == 'POST':
    #     print ("dibya")
    #     # form=UserForm(request.POST)
    #     #email = request.POST.get('email')
    #     username = request.POST.get('username')
    #
    #     password = request.POST.get('password')
    #     print (username,password)
    # return render(request, 'music/badhon.html')
    form = UserForm(request.POST)
    # if request.method == 'POST':
    if form.is_valid():
        # print("form is valid")
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password=form.cleaned_data['password']
        user.set_password(password)
        user.save()
        # print (username)
    #         #email = form.cleaned_data['email']
    #         password=form.cleaned_data['password']
    #         print (username,password)
    #         user.set_password(password)
    #         user.save()
    #

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %}Add Album{% endblock %}
{% block albums_active %}active{% endblock %}
{%  block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">

                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>



</div>
{% endblock %}

music/templates/music/badhon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>{{ username }}</p>
{% for question in all_question %}
    <p>{{ question.text }}</p><br>
{% endfor %}
</body>
</html>

music/templates/music/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}QUORA {% endblock %}</title>
    {% load staticfiles %}
    <link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
{#    <link rel = "stylesheet" type="text/css" href="{% static 'music/style2.css' %}" />#}
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet'type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

     <title>Bootstrap Example</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script><link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-1.11.1.min.js" type="text/javascript" ></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" type="text/javascript" ></script>
<link rel = "stylesheet" type="text/css" href={% static 'music/style3.css' %} />
      <link rel="stylesheet" href="{% static 'css/style5.css' %}">



</head>
<style>

    p.thick {
  font-weight: 900;
        font-size:40px;

}
</style>





<body>

    <nav class="navbar navbar-inverse ">
         <div class="container-fluid">

        <!-- Logo-->
        <div class="navbar-header" >

            <a class="navbar-brand" href="{% url 'music:home' %}">Quora</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href= 'notification/{{ id }}'    >
                        <span class="" aria-hidden="true"></span>
                        Notification
                    </a>
                </li>

            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:search' %}">

                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="{% url 'music:ask_question' %} ">
                       <span class="glyphicon glyphicon-plus" aria-hidden="true">Ask Question</span>
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:home' %} ">
                       <span class="" aria-hidden="true">Profile</span>
                    </a>
                </li>

            </ul>

        </div>



    </div>

    </nav>



    <div class="container-fluid">
  <div class="row">
    <nav class="col-sm-3">
     <div class="vertical-menu">
   <a href="#" class="active"><font size="5">Home</font></a>
  <a href="{% url 'music:menu' "cse" %} "><font size="5">CSE</font></a>
           <a href="{% url 'music:menu' "eee" %} "><font size="5">EEE</font></a>

         <a href="{% url 'music:menu' "mechanical" %} "><font size="5">MECHANICAL</font></a>
         <a href="{% url 'music:menu' "tution" %} "><font size="5">TUTION</font></a>
          <a href="{% url 'music:menu' "robotics" %} "><font size="5">ROBOTICS_CLUB</font></a>
          <a href="{% url 'music:menu' "badhon" %} "><font size="5">BADHON</font></a>
          <a href="#"><font size="5">MURCHONA</font></a>
          <a href="#"><font size="5">CAREER_CLUB</font></a>
          <a href="#"><font size="5">DEBATING CLUB</font></a>
         <a href="#"><font size="5">PHOTOGRAPHIC CLUB</font></a>
           <a href="#"><font size="5">DANCE CLUB</font></a>
           <a href="#"><font size="5">LIBRARY</font></a>
           <a href="#"><font size="5">SPORTS</font></a>







</div>
    </nav>


    <div class="col-sm-7">
    <br>
    <br>

           {% for question in all_question %}
               <div class="jumbotron text-left">

                 <div class="container">

      <p>
        <a href="#" class="btn btn-info btn-mid">
          <span class="glyphicon glyphicon-user"></span> {{ question.person }}
        </a>
      </p>
                     <p>
        <a href="#">
          <span class="glyphicon glyphicon-time"> {{ question.date }}</span>
        </a>
      </p>
    </div>
                <h2>{{ question.tag }}</h2>
            <h3> <a href="{% url 'music:detail1' question.id %}">{{ question.text }}</a></h3>
               </div>
{#               {% csrf_token %}#}
{##}
{#               <p id="demo">JavaScript can change HTML content.</p>#}
{##}
{#<button type="button" onclick='document.getElementById("demo").innerHTML = "Hello JavaScript!"'>Click Me!</button>#}
{#<button type="button" onclick="document.write(5 + 6)">Try it</button>#}
{#               ---using document.write will delete all html content----#}


           {%  endfor %}
    {% if all_question.has_other_pages %}
  <ul class="pagination">
    {% if all_question.has_previous %}
      <li><a href="?page={{ all_question.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in all_question.paginator.page_range %}
      {% if all_question.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if all_question.has_next %}
      <li><a href="?page={{ all_question.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}


    </div>

  </div>
</div>
    <script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>
    <script src="{% static 'js/slidemenu.js' %}"></script>


{% block body %}
{% endblock %}





</body>
</html>

music/templates/music/notification.html
{% extends 'music/base.html' %}

<!DOCTYPE html>
<html lang="en">
{% block head %}

    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% endblock head %}

{% block body %}

{% for notification in notifications %}
    <div class = container>
     <div class="alert alert-info">
     <a href="{% url 'music:detail1' notification.question_id %}" class="alert-link">{{ notification.message }}</a>.
  </div>
    </div>


    {% endfor %}



{% endblock body %}

music/templates/music/request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}QUORA {% endblock %}</title>
    {% load staticfiles %}
    <link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
{#    <link rel = "stylesheet" type="text/css" href="{% static 'music/style2.css' %}" />#}
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet'type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

     <title>Bootstrap Example</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script><link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-1.11.1.min.js" type="text/javascript" ></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" type="text/javascript" ></script>
<link rel = "stylesheet" type="text/css" href={% static 'music/style3.css' %} />
      <link rel="stylesheet" href="{% static 'css/style5.css' %}">



</head>
<style>

    p.thick {
  font-weight: 900;
        font-size:40px;

}
</style>





<body>
{#navbar-fixed-top#}

    <nav class="navbar navbar-inverse ">
         <div class="container-fluid">

        <!-- Logo-->
        <div class="navbar-header" >

            <a class="navbar-brand" href="{% url 'music:home' %}">Quora</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href= "{% url 'music:notification' 22 %}"     >
                        <span class="" aria-hidden="true"></span>
                        Notification
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:home' %}">
                        <span class="" aria-hidden="true"></span>
                        Log In
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:search' %}">

                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="{% url 'music:ask_question' %} ">
                       <span class="glyphicon glyphicon-plus" aria-hidden="true">Ask Question</span>
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:home' %} ">
                       <span class="" aria-hidden="true">Profile</span>
                    </a>
                </li>

            </ul>

        </div>



    </div>

    </nav>



    <div class="container-fluid">
  <div class="row">
    <nav class="col-sm-3">
     <div class="vertical-menu">
          <a href="#" class="active"><font size="5">Home</font></a>
   <a href="{% url 'music:menu' "cse" %} "><font size="5">CSE</font></a>
           <a href="{% url 'music:menu' "eee" %} "><font size="5">EEE</font></a>

         <a href="{% url 'music:menu' "mechanical" %} "><font size="5">MECHANICAL</font></a>
         <a href="{% url 'music:menu' "tution" %} "><font size="5">TUTION</font></a>
          <a href="{% url 'music:menu' "robotics" %} "><font size="5">ROBOTICS_CLUB</font></a>
          <a href="{% url 'music:menu' "badhon" %} "><font size="5">BADHON</font></a>
          <a href="#"><font size="5">MURCHONA</font></a>
          <a href="#"><font size="5">CAREER_CLUB</font></a>
          <a href="#"><font size="5">DEBATING CLUB</font></a>
         <a href="#"><font size="5">PHOTOGRAPHIC CLUB</font></a>
           <a href="#"><font size="5">DANCE CLUB</font></a>
           <a href="#"><font size="5">LIBRARY</font></a>
           <a href="#"><font size="5">SPORTS</font></a>







</div>
    </nav>


    <div class="col-sm-7">
    <br>
    <br>

           {% for question in qsts %}
               <div class="jumbotron text-left">

                 <div class="container">

      <p>
        <a href="#" class="btn btn-info btn-mid">
          <span class="glyphicon glyphicon-user"></span> {{ question.person }}
        </a>
      </p>
                     <p>
        <a href="#">
          <span class="glyphicon glyphicon-time"> {{ question.date }}</span>
        </a>
      </p>
    </div>
                <h2>{{ question.tag }}</h2>
            <h3> <a href="{% url 'music:detail1' question.id %}">{{ question.text }}</a></h3>
               </div>



           {%  endfor %}
    {% if all_question.has_other_pages %}
  <ul class="pagination">
    {% if all_question.has_previous %}
      <li><a href="?page={{ all_question.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in all_question.paginator.page_range %}
      {% if all_question.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if all_question.has_next %}
      <li><a href="?page={{ all_question.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}


    </div>

  </div>
</div>
    <script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>
    <script src="{% static 'js/slidemenu.js' %}"></script>


{% block body %}
{% endblock %}





</body>
</html>